travis:
  secure:
    BINSTAR_TOKEN: odupwZQJk/b4aFZr6K7rnOx+RkamsbevLOGyaQTY1wJCkagdYetqDZWM1z1bJd3XURvyH831zxxO7Z5gmtyPiVQ3iNEKkgwfyqGOWv6w2bb0pgKDd+y5u0AX0UI2qrPUX2VOA1qmowVaaDDQ0MJc+TFQ84xmj4iqs0/UG4uAQGVhvCNKneta53GCS3EQkJTe3husy2ITMEzJ9HqW/foI9d2m3cU448tYBjco8TpZ9gByQ/ehUTMsyoztCrLJw9PzTP6YZEAZAHszB2wSJ5sKNeEjpiyuOb4mr86pyMk8PzIqoRtIl6m16KogQiypZAvSvl4hRH0ciBBq5RZb1JGTM2UDgAoTOso3TGTOxH/kkCO0kEc5tuVjLpx7vkWTMDnBVvUmtKXasnf7LhQKern1MNbP8Wq9NmqKHSNs4kjlY0oohOTABTlc7llKMHxaE1mzdT97fMwUzmTHBzTxITGazrNyqsXVjr9LkgC0s2wBOERiLF6wAHVi3U5/QzhkKfsO49oa/KRwtxfhOWbBH04GhkcQy0SJ85NbAWM63krDlz2X6nY6ZjKbTPZn9IbjGMLBPIyFspY+ACv0dEEPv3tDG3bHv1ntlHKevBbraw0eeX4ndB2HAYc+AoGg2TdqB4viYxi7lYE/dLOqjmr4FhPnxENApPXxxM46BsH+qPWFD64=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
